def hang_man(incorrect):
    if incorrect == 8:
        print("       -------- ")
        print("     |/       | ")
        print("     |          ")
        print("     |          ")
        print("     |          ")
        print("     |          ")
        print("     |          ")
        print("_____|_____     ")
    if incorrect == 7:
        print("       -------- ")
        print("     |/       | ")
        print("     |       (_)")
        print("     |          ")
        print("     |          ")
        print("     |          ")
        print("     |          ")
        print("_____|_____     ")
    if incorrect == 6:
        print("       -------- ")
        print("     |/       | ")
        print("     |       (_)")
        print("     |        | ")
        print("     |        | ")
        print("     |          ")
        print("     |          ")
        print("_____|_____     ")
    if incorrect == 5:
        print("       -------- ")
        print("     |/       | ")
        print("     |       (_)")
        print("     |       \| ")
        print("     |        | ")
        print("     |          ")
        print("     |          ")
        print("_____|_____     ")
    if incorrect == 4:
        print("       -------- ")
        print("     |/       | ")
        print("     |       (_)")
        print("     |       \|/")
        print("     |        | ")
        print("     |          ")
        print("     |          ")
        print("_____|_____     ")
    if incorrect == 3:
        print("       -------- ")
        print("     |/       | ")
        print("     |       (_)")
        print("     |       \|/")
        print("     |        | ")
        print("     |       /  ")
        print("     |          ")
        print("_____|_____     ")
    if incorrect == 2:
        print("       -------- ")
        print("     |/       | ")
        print("     |       (_)")
        print("     |       \|/")
        print("     |        | ")
        print("     |       / \\")
        print("     |          ")
        print("_____|_____     ")
    if incorrect == 1:
        print("       -------- ")
        print("     |/       | ")
        print("     |       (_)")
        print("     |       \|/")
        print("     |        | ")
        print("     |      _/ \\")
        print("     |          ")
        print("_____|_____     ")
    if incorrect == 0:
        print("       -------- ")
        print("     |/       | ")
        print("     |       (_)")
        print("     |       \|/")
        print("     |        | ")
        print("     |      _/ \_")
        print("     |          ")
        print("_____|_____     ")
